#ifndef GUARD_CONFIG_H
#define GUARD_CONFIG_H

// In the Generation 3 games, Asserts were used in various debug builds.
// Ruby/Sapphire and Emerald do not have these asserts while Fire Red
// still has them in the ROM. This is because the developers forgot
// to define NDEBUG before release, however this has been changed as
// Ruby's actual debug build does not use the AGBPrint features.
#define NDEBUG

// To enable printf debugging, comment out "#define NDEBUG". This allows
// the various AGBPrint functions to be used. (See include/gba/isagbprint.h).
// See below for enabling different pretty printing versions.

#ifndef NDEBUG

#define PRETTY_PRINT_MINI_PRINTF (0)
#define PRETTY_PRINT_LIBC (1)

#define LOG_HANDLER_AGB_PRINT (0)
#define LOG_HANDLER_NOCASH_PRINT (1)
#define LOG_HANDLER_MGBA_PRINT (2)

// Use this switch to choose a handler for pretty printing.
// NOTE: mini_printf supports a custom pretty printing formatter to display preproc encoded strings. (%S)
//       some libc distributions (especially dkp arm-libc) will fail to link pretty printing.
#define PRETTY_PRINT_HANDLER (PRETTY_PRINT_MINI_PRINTF)

// Use this switch to choose a handler for printf output.
// NOTE: These will only work on the respective emulators and should not be used in a productive environment.
//       Some emulators or real hardware might (and is allowed to) crash if they are used.
//       AGB_PRINT is supported on respective debug units.

#define LOG_HANDLER (LOG_HANDLER_MGBA_PRINT)
#endif

#define ENGLISH

#ifdef ENGLISH
#define UNITS_IMPERIAL
#define CHAR_DEC_SEPARATOR CHAR_PERIOD // Period is used as a decimal separator only in the UK and the US.
#else
#define UNITS_METRIC
#define CHAR_DEC_SEPARATOR CHAR_COMMA
#endif

// ====================================================================
// Optional mods (agent_tools toggleable via tweak_config.py)
// Set any of these to a non-zero value to enable the mod.
// ====================================================================

// Every Pokémon generated by CreateBoxMon receives 31 IVs in all 6 stats.
#define PERFECT_IVS 1

// Integer multiplier applied to calculatedExp in battle_script_commands.c.
// 1 = vanilla, 2 = double exp, 4 = quadruple, etc.
#define EXP_MULTIPLIER 3

// Integer multiplier applied to capture odds before the shake calculation.
// 1 = vanilla, 3 = roughly Ultra-Ball-on-everything, 999 = near guaranteed.
#define CATCH_RATE_BONUS 3

// If non-zero, player-initiated moves never miss (the Random() accuracy
// roll is skipped when the attacker is on the player's side).
#define NEVER_MISS 1

// Integer added to the critChance stage index before rolling crits.
// 0 = vanilla, 3 = always crit (index saturates to the max table slot).
#define CRIT_RATE_BONUS 0

// If non-zero, StandardWildEncounter() returns FALSE immediately.
#define NO_RANDOM_ENCOUNTERS 0

// If non-zero, TMs are not consumed on use (HMs already aren't).
#define UNLIMITED_TMS 1

// Starting money the player receives from the new-game init. Vanilla = 3000.
#define STARTING_MONEY 30000

// If non-zero, GetPlayerTextSpeedDelay() returns 0 — all text is instant.
#define INSTANT_TEXT 1

// If non-zero, you can run on every map (ignores gMapHeader.allowRunning).
// Per-metatile disallow (tall grass, etc.) is still respected.
#define RUN_ANYWHERE 1

// If non-zero, the Latios/Latias intro cinematic is skipped.
#define SKIP_INTRO 1

// If non-zero, catching a Pokémon awards experience to every alive party
// member (divided evenly) as if the caught Pokémon had fainted.
#define CATCH_EXP 1

// If non-zero, every alive party member gains exp from each KO, divided
// evenly. Mirrors the Gen 6+ "Exp. Share item is always on" behavior.
#define EXP_ALL 1

// If non-zero, field-poison ticks stop at 1 HP instead of fainting your
// Pokémon while walking. The mon still takes the damage tick but won't
// white out from poison on the overworld.
#define POISON_DOESNT_FAINT 1

// If non-zero, each move's Physical / Special / Status category is read
// from its .split field instead of being derived from the move's type.
// Matches Gen 4+ behavior (Shadow Ball → Special, Ice Punch → Physical).
// When off, vanilla type-based split is used and the .split field is
// ignored. See include/constants/battle_split.h.
#define PHYSICAL_SPECIAL_SPLIT 1

// If non-zero, starting a new game skips the intro/truck sequence and
// drops the player on Route 102 with a pre-built test party designed to
// exercise the Physical/Special split (Alakazam + Machamp + Gardevoir,
// each at Lv 50 with split-sensitive movesets). Overrides WarpToTruck.
// Use to quickly sanity-check battle-side mods without a full playthrough.
#define QUICK_TEST 1

// Uncomment to fix some identified minor bugs
//#define BUGFIX

// Various undefined behavior bugs may or may not prevent compilation with
// newer compilers. So always fix them when using a modern compiler.
#if MODERN || defined(BUGFIX)
#ifndef UBFIX
#define UBFIX
#endif
#endif

#endif // GUARD_CONFIG_H
